include:
  - board: nice_nano@2.0.0
    shield: corne_left
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: corne_right
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: sofle_left
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: sofle_right
    snippet: zmk-usb-logging
